import { json, type MetaFunction } from '@remix-run/cloudflare';
import { PageLayout } from '~/components/layout/PageLayout';
import { useState } from 'react';

export const meta: MetaFunction = () => {
  return [
    { title: 'Clyra.ai || Next Gen Ai Assistant' },
    { name: 'description', content: 'The terms and conditions (T&C) governing the use of your app or service. It outlines user rights, responsibilities, limitations, and legal agreements.' },
  ];
};

export const loader = () => json({});

interface TermSection {
  id: string;
  title: string;
  content: string;
  defaultExpanded?: boolean;
}

const termsSections: TermSection[] = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `
      By accessing and using Clyra.ai ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
      
      These Terms of Service ("Terms") govern your use of Clyra.ai's AI development platform, APIs, and related services (collectively, the "Service") operated by Clyra.ai ("we," "us," or "our").
      
      Your use of the Service constitutes your acceptance of these Terms, our Privacy Policy, and any other legal notices published on our website. If you do not agree to these Terms, you must not access or use the Service.
    `,
    defaultExpanded: true
  },
  {
    id: 'description',
    title: '2. Service Description',
    content: `
      Clyra.ai provides an AI development platform that includes:
      
      • AI-powered chat and conversation interfaces
      • Code generation and development assistance
      • API access to various AI models
      • Project management and collaboration tools
      • Documentation and learning resources
      
      We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time with or without notice. We will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Service.
    `
  },
  {
    id: 'user-responsibilities',
    title: '3. User Responsibilities',
    content: `
      As a user of Clyra.ai, you agree to:
      
      • Provide accurate and complete information when creating an account
      • Maintain the security of your account credentials
      • Use the Service in compliance with all applicable laws and regulations
      • Not attempt to gain unauthorized access to our systems or other users' accounts
      • Not use the Service for any illegal or unauthorized purpose
      • Not interfere with or disrupt the Service or servers connected to the Service
      • Not upload malicious code, viruses, or harmful content
      • Respect the intellectual property rights of others
      • Not use the Service to generate content that is harmful, offensive, or violates any laws
      
      You are solely responsible for your use of the Service and any content you create or share using our platform.
    `
  },
  {
    id: 'intellectual-property',
    title: '4. Intellectual Property Rights',
    content: `
      **Our Rights**
      The Service and its original content, features, and functionality are and will remain the exclusive property of Clyra.ai and its licensors. The Service is protected by copyright, trademark, and other laws.
      
      **Your Content**
      You retain ownership of any content you create, upload, or share using the Service. However, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and analyze your content solely to provide and improve the Service.
      
      **Generated Content**
      Content generated by our AI models is owned by you. However, we may use anonymized data from AI interactions to improve our models and services, in accordance with our Privacy Policy.
      
      **Trademarks**
      Clyra.ai, the Clyra.ai logo, and all related trademarks, trade names, and other intellectual property are the exclusive property of Clyra.ai and may not be used without our prior written consent.
    `
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use Policy',
    content: `
      **Prohibited Uses**
      You may not use the Service to:
      
      • Generate or distribute illegal content or conduct illegal activities
      • Create content that violates the rights of others (copyright, privacy, etc.)
      • Develop weapons, facilitate violence, or promote harmful activities
      • Engage in harassment, abuse, or hate speech
      • Spread misinformation or malicious content
      • Attempt to reverse engineer or extract our AI models
      • Use the Service for spam, fraud, or deceptive practices
      • Violate any applicable laws or regulations
      
      **Content Moderation**
      We reserve the right to review and remove content that violates these terms. We may also suspend or terminate accounts that repeatedly violate our policies.
      
      **Reporting Violations**
      If you believe someone is violating these terms, please report them to our support team at support@clyra.ai.
    `
  },
  {
    id: 'privacy-and-data',
    title: '6. Privacy and Data Protection',
    content: `
      Your privacy is important to us. Our use of your personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
      
      **Data Collection**
      We collect information necessary to provide and improve our services, including:
      • Account information and authentication data
      • Usage patterns and interaction data
      • Content you create or share
      • Technical and diagnostic information
      
      **Data Use**
      We use your data to:
      • Provide and maintain the Service
      • Improve our AI models and features
      • Ensure security and prevent fraud
      • Communicate with you about the Service
      
      **Data Sharing**
      We do not sell your personal information. We may share data with service providers who help us operate the Service, as detailed in our Privacy Policy.
      
      **Your Rights**
      You have rights to access, correct, and delete your personal information. Contact us at privacy@clyra.ai to exercise these rights.
    `
  },
  {
    id: 'payment-and-subscription',
    title: '7. Payment and Subscription Terms',
    content: `
      **Free and Paid Plans**
      We offer both free and paid subscription plans. Free plans have usage limitations, while paid plans provide additional features and higher usage limits.
      
      **Billing**
      • Paid subscriptions are billed in advance on a monthly or annual basis
      • All fees are non-refundable except as required by law
      • We may change our pricing with 30 days notice
      • Taxes may apply based on your location
      
      **Payment Methods**
      We accept major credit cards and other payment methods as listed on our website. You agree to provide current, complete, and accurate payment information.
      
      **Auto-Renewal**
      Subscriptions automatically renew unless cancelled before the renewal date. You can cancel your subscription at any time through your account settings.
      
      **Failed Payments**
      If a payment fails, we may suspend your access to paid features until payment is successfully processed.
    `
  },
  {
    id: 'service-availability',
    title: '8. Service Availability and Performance',
    content: `
      **Uptime Commitment**
      We strive to maintain high availability of the Service, targeting 99.9% uptime. However, we cannot guarantee uninterrupted service and may experience downtime for maintenance or technical issues.
      
      **Service Levels**
      • Different plans may have different service level commitments
      • We may implement rate limits to ensure fair usage
      • Service availability may vary by geographic region
      
      **Maintenance**
      We may perform scheduled maintenance with advance notice when possible. Emergency maintenance may be required without notice.
      
      **No Warranties**
      The Service is provided "as is" without warranties of any kind. We do not guarantee that the Service will meet your requirements or be error-free.
    `
  },
  {
    id: 'limitation-of-liability',
    title: '9. Limitation of Liability',
    content: `
      **Disclaimer of Warranties**
      To the maximum extent permitted by law, Clyra.ai disclaims all warranties, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.
      
      **Limitation of Damages**
      In no event shall Clyra.ai, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the Service.
      
      **Maximum Liability**
      Our total liability to you for any claims arising from these Terms or the Service shall not exceed the amount you paid to us in the twelve (12) months preceding the claim, or $100, whichever is greater.
      
      **Exceptions**
      Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, so the above limitation may not apply to you.
    `
  },
  {
    id: 'termination',
    title: '10. Account Termination',
    content: `
      **Termination by You**
      You may terminate your account at any time by:
      • Following the account deletion process in your settings
      • Contacting our support team at support@clyra.ai
      
      **Termination by Us**
      We may terminate or suspend your account immediately, without prior notice or liability, for any reason, including if you:
      • Breach these Terms of Service
      • Violate our Acceptable Use Policy
      • Engage in fraudulent or illegal activities
      • Compromise the security of the Service
      
      **Effect of Termination**
      Upon termination:
      • Your right to use the Service ceases immediately
      • We may delete your account and data, though we may retain certain information as required by law
      • Any provisions that by their nature should survive termination will continue to apply
      • You will not be entitled to any refund for unused portions of your subscription
      
      **Data Export**
      Before terminating your account, you can export your data using our data export tools.
    `
  },
  {
    id: 'governing-law',
    title: '11. Governing Law and Dispute Resolution',
    content: `
      **Governing Law**
      These Terms shall be interpreted and governed by the laws of the State of California, United States, without regard to conflict of law provisions.
      
      **Dispute Resolution**
      Any disputes arising from these Terms or the Service will be resolved through:
      
      1. **Informal Negotiation**: First, we encourage you to contact us directly to resolve any issues
      2. **Mediation**: If informal resolution fails, disputes will be resolved through mediation
      3. **Arbitration**: If mediation fails, disputes will be resolved through binding arbitration
      
      **Arbitration Details**
      • Arbitration will be conducted by the American Arbitration Association
      • The arbitration will be conducted in English
      • The decision of the arbitrator will be final and binding
      • Each party bears its own costs of arbitration
      
      **Class Action Waiver**
      You agree to resolve disputes individually and waive any right to participate in class actions or class-wide arbitration.
      
      **Jurisdiction**
      You consent to the exclusive jurisdiction of state and federal courts located in San Francisco, California for any matters not subject to arbitration.
    `
  },
  {
    id: 'changes-to-terms',
    title: '12. Changes to These Terms',
    content: `
      **Right to Modify**
      We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting.
      
      **Notification**
      We will notify you of material changes by:
      • Email notification to registered users
      • In-app notifications
      • Posting on our website
      • Other appropriate communication methods
      
      **Your Options**
      If you disagree with any changes to these Terms, you may:
      • Terminate your account and stop using the Service
      • Contact us to discuss your concerns
      
      **Continued Use**
      Your continued use of the Service after changes are posted constitutes acceptance of the modified Terms.
      
      **Review Period**
      We encourage you to review these Terms periodically to stay informed about your rights and responsibilities.
    `
  },
  {
    id: 'contact-information',
    title: '13. Contact Information',
    content: `
      If you have questions about these Terms of Service, please contact us:
      
      **General Inquiries**
      • Email: legal@clyra.ai
      • Phone: +1 (555) 123-4567
      • Mail: Legal Department, Clyra.ai, 123 Tech Street, San Francisco, CA 94105
      
      **Support**
      • Email: support@clyra.ai
      • Help Center: https://help.clyra.ai
      • Live Chat: Available in your dashboard
      
      **Data Protection**
      • Email: privacy@clyra.ai
      • DPO (EU): dpo@clyra.ai
      
      **Business Hours**
      Our support team is available Monday through Friday, 9:00 AM to 6:00 PM Pacific Time, excluding major holidays.
      
      **Emergency Contacts**
      For urgent security or legal matters, contact our emergency hotline at +1 (555) 911-HELP.
    `
  }
];

function CollapsibleSection({ section, isExpanded, onToggle }: { 
  section: TermSection; 
  isExpanded: boolean; 
  onToggle: () => void;
}) {
  return (
    <div className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-2xl border border-accent-200/60 shadow-lg overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full px-8 py-6 text-left flex items-center justify-between hover:bg-accent-50 dark:hover:bg-accent-900/20 transition-colors duration-200"
      >
        <h3 className="text-xl font-semibold text-bolt-elements-textPrimary">
          {section.title}
        </h3>
        <div className={`transform transition-transform duration-200 ${
          isExpanded ? 'rotate-180' : ''
        }`}>
          <span className="i-ph:caret-down text-2xl text-bolt-elements-textSecondary"></span>
        </div>
      </button>
      
      <div className={`transition-all duration-300 ease-in-out ${
        isExpanded ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
      } overflow-hidden`}>
        <div className="px-8 pb-6">
          <div className="prose prose-lg max-w-none text-bolt-elements-textSecondary">
            {section.content.split('\n').map((paragraph, index) => {
              if (paragraph.trim() === '') return null;
              if (paragraph.startsWith('•')) {
                return (
                  <li key={index} className="ml-4 mb-2">
                    {paragraph.replace('•', '').trim()}
                  </li>
                );
              }
              if (paragraph.startsWith('**')) {
                return (
                  <h4 key={index} className="font-semibold text-lg mb-3 mt-4">
                    {paragraph.replace(/\*\*/g, '').trim()}
                  </h4>
                );
              }
              return (
                <p key={index} className="mb-4 leading-relaxed">
                  {paragraph.trim()}
                </p>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function Terms() {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(termsSections.filter(s => s.defaultExpanded).map(s => s.id))
  );

  const toggleSection = (sectionId: string) => {
    setExpandedSections(prev => {
      const newSet = new Set(prev);
      if (newSet.has(sectionId)) {
        newSet.delete(sectionId);
      } else {
        newSet.add(sectionId);
      }
      return newSet;
    });
  };

  const expandAll = () => {
    setExpandedSections(new Set(termsSections.map(s => s.id)));
  };

  const collapseAll = () => {
    setExpandedSections(new Set());
  };

  return (
    <PageLayout 
      title="Terms of Service" 
      description="The terms and conditions (T&C) governing the use of your app or service. It outlines user rights, responsibilities, limitations, and legal agreements."
    >
      <div className="max-w-4xl mx-auto">
        {/* Header Actions */}
        <div className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-2xl border border-accent-200/60 p-6 mb-8 shadow-lg">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <h3 className="text-lg font-semibold text-bolt-elements-textPrimary mb-2">
                Document Controls
              </h3>
              <p className="text-sm text-bolt-elements-textSecondary">
                Last updated: November 6, 2024
              </p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={expandAll}
                className="px-4 py-2 bg-[#4DA8FF]/10 text-[#4DA8FF] font-medium rounded-lg hover:bg-[#4DA8FF]/20 transition-colors duration-200"
              >
                Expand All
              </button>
              <button
                onClick={collapseAll}
                className="px-4 py-2 bg-accent-100 dark:bg-accent-800 text-bolt-elements-textSecondary font-medium rounded-lg hover:bg-accent-200 dark:hover:bg-accent-700 transition-colors duration-200"
              >
                Collapse All
              </button>
            </div>
          </div>
        </div>

        {/* Quick Links */}
        <div className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-2xl border border-accent-200/60 p-6 mb-8 shadow-lg">
          <h3 className="text-lg font-semibold text-bolt-elements-textPrimary mb-4">
            Quick Links
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
            {termsSections.map((section) => (
              <button
                key={section.id}
                onClick={() => toggleSection(section.id)}
                className="text-left text-sm text-bolt-elements-textSecondary hover:text-[#4DA8FF] transition-colors py-2 px-3 rounded-lg hover:bg-accent-100 dark:hover:bg-accent-800"
              >
                {section.title}
              </button>
            ))}
          </div>
        </div>

        {/* Terms Sections */}
        <div className="space-y-4 mb-8">
          {termsSections.map((section) => (
            <CollapsibleSection
              key={section.id}
              section={section}
              isExpanded={expandedSections.has(section.id)}
              onToggle={() => toggleSection(section.id)}
            />
          ))}
        </div>

        {/* Legal Notice */}
        <div className="bg-gradient-to-r from-[#4DA8FF]/10 to-[#2C8CFF]/10 rounded-2xl border border-accent-200/60 p-8 text-center">
          <h3 className="text-xl font-bold text-bolt-elements-textPrimary mb-4">
            Legal Notice
          </h3>
          <p className="text-bolt-elements-textSecondary mb-6">
            This document is a legal agreement between you and Clyra.ai. Please read it carefully before using our Service. If you have any questions, consult with a legal professional.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="px-6 py-3 bg-gradient-to-r from-[#4DA8FF] to-[#2C8CFF] text-white font-semibold rounded-xl hover:shadow-lg transition-all duration-200 flex items-center justify-center gap-2">
              <span className="i-ph:download-simple"></span>
              Download PDF
            </button>
            <button className="px-6 py-3 bg-white/80 dark:bg-gray-900/80 text-bolt-elements-textPrimary font-semibold rounded-xl border border-accent-200/60 hover:border-[#4DA8FF] transition-all duration-200 flex items-center justify-center gap-2">
              <span className="i-ph:printer"></span>
              Print Terms
            </button>
          </div>
        </div>

        {/* Contact Information */}
        <div className="text-center mt-8 text-sm text-bolt-elements-textSecondary">
          <p>For questions about these Terms of Service, contact our legal team at legal@clyra.ai</p>
          <p className="mt-2">© 2024 Clyra.ai. All rights reserved.</p>
        </div>
      </div>
    </PageLayout>
  );
}
